/* Sage Stage — default English packs (design: docs/english-widgets-design.md §4.4, §9).
   Pure data, like templates.js. One envelope (sage-pack@1), six kinds eventually;
   two are here now — phonics (phoneme tiles) and genre (the genre toolkit,
   docs/genre-toolkit-design.md §13). Everything here is either our own wording
   or Crown-copyright material used under the Open Government Licence v3 — branded
   scheme content (RWI, Little Wandle, Jolly Phonics…) is never shipped; schools
   paste their scheme's wording into their own packs (§11).

   The genre packs' criteria use National Curriculum terminology (fronted
   adverbial, relative clause, expanded noun phrase, modal verb) freely — that is
   Crown copyright under OGL — but the criteria themselves are worded here, and no
   scheme's phrasing appears. `model` is empty in every one of them on purpose: a
   school's WAGOLL is a school's own, and a published model text is somebody's
   copyright (genre-toolkit-design.md §3). */
window.SAGE_ENGLISH_PACKS = [
  {
    format: 'sage-pack@1',
    kind: 'phonics',
    id: 'letters-and-sounds-2007',
    name: 'Letters and Sounds (2007)',
    author: 'Sage Stage',
    note: 'GPC teaching order and tricky words from the DfE "Letters and Sounds" (2007) — Crown copyright, Open Government Licence v3. Phase 1 is oral (no graphemes); Phase 4 introduces adjacent consonants, no new GPCs; split digraphs use a_e notation.',
    phases: [
      {
        id: '2', name: 'Phase 2',
        sets: [
          ['s', 'a', 't', 'p'],
          ['i', 'n', 'm', 'd'],
          ['g', 'o', 'c', 'k'],
          ['ck', 'e', 'u', 'r'],
          ['h', 'b', 'f', 'ff', 'l', 'll', 'ss'],
        ],
        tricky: ['the', 'to', 'I', 'no', 'go', 'into'],
      },
      {
        id: '3', name: 'Phase 3',
        sets: [
          ['j', 'v', 'w', 'x'],
          ['y', 'z', 'zz', 'qu'],
          ['ch', 'sh', 'th', 'ng'],
          ['ai', 'ee', 'igh', 'oa'],
          ['oo', 'ar', 'or', 'ur'],
          ['ow', 'oi', 'ear', 'air'],
          ['ure', 'er'],
        ],
        tricky: ['he', 'she', 'we', 'me', 'be', 'was', 'you', 'they', 'all', 'are', 'my', 'her'],
      },
      {
        id: '4', name: 'Phase 4',
        sets: [], // adjacent consonants — no new GPCs; the tray stays cumulative
        tricky: ['said', 'have', 'like', 'so', 'do', 'some', 'come', 'were', 'there', 'little', 'one', 'when', 'out', 'what'],
      },
      {
        id: '5', name: 'Phase 5',
        sets: [
          ['ay', 'ou', 'ie', 'ea'],
          ['oy', 'ir', 'ue', 'aw'],
          ['wh', 'ph', 'ew', 'oe'],
          ['au', 'a_e', 'e_e', 'i_e'],
          ['o_e', 'u_e'],
        ],
        tricky: ['oh', 'their', 'people', 'Mr', 'Mrs', 'looked', 'called', 'asked', 'could'],
      },
    ],
  },

  // ---------------------------------------------------------------- genre packs
  // All twelve of §9's list, in §9's order. The first four to ship (narrative,
  // newspaper report, explanation, persuasion) were chosen to span the text
  // types so the widget was proven against real variety; the other eight landed
  // 2026-07-28 as the data-only follow-up pass (genre-toolkit-design.md §2).
  //
  // Bands are ks1 (Reception–Y2), lks2 (Y3–4), uks2 (Y5–6). Three, not seven: a
  // criterion does not change between Year 3 and Year 4, and a criterion the
  // class has outgrown is one the teacher deletes rather than one we predicted.
  {
    format: 'sage-pack@1',
    kind: 'genre',
    id: 'narrative',
    name: 'Narrative',
    author: 'Sage Stage',
    note: 'Story writing across the primary range. The KS1 criteria are about getting a whole story down; the upper KS2 ones are about controlling how it lands on a reader.',
    items: [
      { t: 'A beginning that says who and where', band: 'ks1' },
      { t: 'Joining words: and, but, so', band: 'ks1' },
      { t: 'A capital letter and a full stop in every sentence', band: 'ks1' },
      { t: 'Describing words for the characters', band: 'ks1' },
      { t: 'A problem the character has to solve', band: 'ks1' },
      { t: 'An opening that sets the scene', band: 'lks2' },
      { t: 'Fronted adverbials with a comma', band: 'lks2' },
      { t: 'Expanded noun phrases to describe', band: 'lks2' },
      { t: 'Speech inside inverted commas', band: 'lks2' },
      { t: 'Paragraphs to show a change of time or place', band: 'lks2' },
      { t: 'An ending that solves the problem', band: 'lks2' },
      { t: 'An opening that hooks — action, speech or setting', band: 'uks2' },
      { t: 'Relative clauses to add detail', band: 'uks2' },
      { t: 'Show, don’t tell: feelings through action', band: 'uks2' },
      { t: 'Sentence lengths varied for pace', band: 'uks2' },
      { t: 'Dialogue that moves the story on', band: 'uks2' },
      { t: 'An ending that echoes the opening', band: 'uks2' },
    ],
    structure: [
      { box: 'Opening', hint: 'Who, where, when — and a reason to read on' },
      { box: 'Build-up', hint: 'Something starts to go wrong' },
      { box: 'Problem', hint: 'The moment it all goes wrong' },
      { box: 'Resolution', hint: 'How it is put right' },
      { box: 'Ending', hint: 'How things are now, and what changed' },
    ],
    language: {
      openers: ['Early one morning', 'Without warning', 'As soon as', 'Long before dawn',
        'Deep in the forest', 'The moment she turned', 'By the time anyone noticed',
        'Somewhere behind them'],
      connectives: ['meanwhile', 'suddenly', 'until then', 'at last', 'moments later',
        'all the while', 'no sooner', 'even so'],
      vocabulary: ['glanced', 'hesitated', 'trembling', 'deserted', 'whispered', 'edged',
        'frantic', 'gloom', 'brittle', 'sank'],
    },
    model: '',
  },
  {
    format: 'sage-pack@1',
    kind: 'genre',
    id: 'recount',
    name: 'Recount',
    author: 'Sage Stage',
    note: 'The genre every school trip comes home to. KS1 puts the day in order; upper KS2 turns a list of events into something a reader would want to read back.',
    items: [
      { t: 'Who went, and where', band: 'ks1' },
      { t: 'What happened, in the order it happened', band: 'ks1' },
      { t: 'Past tense: went, saw, made', band: 'ks1' },
      { t: 'Time words: first, next, then, after that', band: 'ks1' },
      { t: 'An opening that sets the scene: who, where, when', band: 'lks2' },
      { t: 'Paragraphs in time order', band: 'lks2' },
      { t: 'Fronted adverbials of time, with a comma', band: 'lks2' },
      { t: 'Detail that puts the reader there', band: 'lks2' },
      { t: 'A closing that says how it ended', band: 'lks2' },
      { t: 'An opening that answers the 5 Ws without listing them', band: 'uks2' },
      { t: 'Events chosen for interest — not everything that happened', band: 'uks2' },
      { t: 'Cohesion across paragraphs: meanwhile, later that day, by evening', band: 'uks2' },
      { t: 'Your thoughts and reactions woven through the events', band: 'uks2' },
      { t: 'A reflective ending — what it meant, not just what came last', band: 'uks2' },
    ],
    structure: [
      { box: 'Opening', hint: 'Who went, where, when — and why' },
      { box: 'First', hint: 'How it began' },
      { box: 'Then', hint: 'The main events, in the order they happened' },
      { box: 'Finally', hint: 'How it ended' },
      { box: 'Looking back', hint: 'What you thought and felt about it' },
    ],
    language: {
      openers: ['Last Tuesday', 'First thing in the morning', 'As soon as we arrived',
        'After lunch', 'Later that day', 'Just before home time', 'On the way back',
        'When we finally got there'],
      connectives: ['first', 'next', 'after that', 'meanwhile', 'later', 'eventually',
        'at last', 'finally'],
      vocabulary: ['set off', 'arrived', 'explored', 'discovered', 'gathered', 'amazed',
        'fascinating', 'exhausted', 'memorable', 'souvenir'],
    },
    model: '',
  },
  {
    format: 'sage-pack@1',
    kind: 'genre',
    id: 'diary',
    name: 'Diary',
    author: 'Sage Stage',
    note: 'A recount nobody else was meant to read — which is exactly the voice being taught. KS1 gets the day down as I; KS2 works on feeling, hindsight and a voice that sounds like a person.',
    items: [
      { t: 'The date at the top', band: 'ks1' },
      { t: 'Written as I — it happened to you', band: 'ks1' },
      { t: 'What happened today, in order', band: 'ks1' },
      { t: 'How each part made you feel', band: 'ks1' },
      { t: 'An opening line that sets the mood of the day', band: 'lks2' },
      { t: 'Past tense for events, present for feelings: I still can’t believe it', band: 'lks2' },
      { t: 'Informal words, like talking to a friend', band: 'lks2' },
      { t: 'Exclamations and questions to show feeling', band: 'lks2' },
      { t: 'Time adverbials to move through the day', band: 'lks2' },
      { t: 'A voice that sounds like you, kept up all the way through', band: 'uks2' },
      { t: 'Thoughts, hopes and worries — not just events', band: 'uks2' },
      { t: 'Short sentences where the feeling is strongest', band: 'uks2' },
      { t: 'Hindsight: what you know now that you didn’t know then', band: 'uks2' },
      { t: 'An ending that looks to tomorrow', band: 'uks2' },
    ],
    structure: [
      { box: 'Date', hint: 'And Dear Diary, if that’s your style' },
      { box: 'How today felt', hint: 'One line that sets the mood' },
      { box: 'What happened', hint: 'The day in order, with your side of it' },
      { box: 'The big moment', hint: 'The part you’ll remember — slow it down' },
      { box: 'Tomorrow', hint: 'What you hope, dread or plan' },
    ],
    language: {
      openers: ['Dear Diary', 'What a day this has been', 'You will never guess what',
        'I woke up this morning to', 'By the time I got home', 'I have never been so',
        'Today started like any other day', 'Looking back on it now'],
      connectives: ['then', 'after that', 'luckily', 'unfortunately', 'to make things worse',
        'best of all', 'in the end', 'even now'],
      vocabulary: ['thrilled', 'mortified', 'dreading', 'relieved', 'furious', 'speechless',
        'butterflies', 'exhausted', 'secretly', 'unforgettable'],
    },
    model: '',
  },
  {
    format: 'sage-pack@1',
    kind: 'genre',
    id: 'letter',
    name: 'Letter',
    author: 'Sage Stage',
    note: 'One journey from thank-you note to formal complaint. The KS1 criteria get a letter to its reader; the upper KS2 ones choose the register the reader expects.',
    items: [
      { t: 'Dear, then the person’s name', band: 'ks1' },
      { t: 'Says why you are writing', band: 'ks1' },
      { t: 'A question for the reader — letters talk back', band: 'ks1' },
      { t: 'From, or love from, and your name', band: 'ks1' },
      { t: 'The address and the date in the right place', band: 'lks2' },
      { t: 'A first line that says why you are writing', band: 'lks2' },
      { t: 'A paragraph for each thing you want to say', band: 'lks2' },
      { t: 'Polite phrases: thank you for, please could, I would love to', band: 'lks2' },
      { t: 'A closing line that says what you hope happens next', band: 'lks2' },
      { t: 'Formal or friendly — chosen for the reader, kept up throughout', band: 'uks2' },
      { t: 'Yours sincerely to a name, Yours faithfully to Dear Sir or Madam', band: 'uks2' },
      { t: 'Formal phrases: I am writing to, I would be grateful if', band: 'uks2' },
      { t: 'Modal verbs to sound firm but polite: would, could, should', band: 'uks2' },
      { t: 'A final paragraph that asks plainly for what you want', band: 'uks2' },
    ],
    structure: [
      { box: 'Address and date', hint: 'Yours, top right' },
      { box: 'Dear…', hint: 'The name, then a comma' },
      { box: 'Why I am writing', hint: 'Say it in the first line' },
      { box: 'The detail', hint: 'A paragraph for each point' },
      { box: 'What happens next', hint: 'What you hope for, or are asking for' },
      { box: 'Sign-off', hint: 'Sincerely to a name, faithfully to a stranger — or love from' },
    ],
    language: {
      openers: ['I am writing to', 'Thank you so much for', 'I was delighted to hear',
        'I am sorry to say', 'You will be pleased to know', 'I wonder if you could',
        'It has been so long since', 'I must tell you about'],
      connectives: ['firstly', 'also', 'as well as this', 'however', 'therefore',
        'in future', 'once again', 'finally'],
      vocabulary: ['grateful', 'delighted', 'disappointed', 'sincerely', 'faithfully',
        'request', 'apologise', 'enquire', 'urgent', 'regards'],
    },
    model: '',
  },
  {
    format: 'sage-pack@1',
    kind: 'genre',
    id: 'instructions',
    name: 'Instructions',
    author: 'Sage Stage',
    note: 'How to do it, for a reader who cannot ask questions. KS1 learns that order is everything; KS2 learns precision — one action per step, and the words doing all the work.',
    items: [
      { t: 'A title that says what you are making: How to…', band: 'ks1' },
      { t: 'What you need, as a list', band: 'ks1' },
      { t: 'Steps numbered, in order', band: 'ks1' },
      { t: 'Bossy verbs first: cut, stick, mix', band: 'ks1' },
      { t: 'A “you will need” list with amounts', band: 'lks2' },
      { t: 'One action per step', band: 'lks2' },
      { t: 'Imperative verbs to start each step', band: 'lks2' },
      { t: 'Adverbs that say how: carefully, slowly, gently', band: 'lks2' },
      { t: 'A tip where the reader might go wrong', band: 'lks2' },
      { t: 'An opening that says what the reader will end up with', band: 'uks2' },
      { t: 'Precise amounts, times and measurements', band: 'uks2' },
      { t: 'Brackets for a tip or a warning inside a step', band: 'uks2' },
      { t: 'Technical vocabulary where precision needs it', band: 'uks2' },
      { t: 'The stranger test: could they follow it without asking you anything?', band: 'uks2' },
    ],
    structure: [
      { box: 'Title', hint: 'How to…' },
      { box: 'What you need', hint: 'Everything, with amounts' },
      { box: 'Steps', hint: 'Numbered, one action each, verb first' },
      { box: 'Tips', hint: 'Where it goes wrong, and how not to' },
      { box: 'The result', hint: 'How to tell it has worked' },
    ],
    language: {
      openers: ['First', 'Before you begin', 'Once you have done this', 'While you wait',
        'When it is ready', 'Next', 'After a few minutes', 'To finish'],
      connectives: ['first', 'next', 'then', 'while', 'until', 'once', 'before', 'when'],
      vocabulary: ['carefully', 'gently', 'firmly', 'gradually', 'exactly', 'attach',
        'measure', 'repeat', 'check', 'equipment'],
    },
    model: '',
  },
  {
    format: 'sage-pack@1',
    kind: 'genre',
    id: 'explanation',
    name: 'Explanation',
    author: 'Sage Stage',
    note: 'How and why something works — the genre science, history and geography write-ups actually live in. Cross-curricular by nature (§13 of the English set design).',
    items: [
      { t: 'A title that says what you are explaining', band: 'ks1' },
      { t: 'The steps in the right order', band: 'ks1' },
      { t: 'Using “because” to give a reason', band: 'ks1' },
      { t: 'A labelled picture', band: 'ks1' },
      { t: 'An opening that says what is being explained', band: 'lks2' },
      { t: 'Present tense all the way through', band: 'lks2' },
      { t: 'Time connectives to sequence the steps', band: 'lks2' },
      { t: 'Causal conjunctions: because, so, so that', band: 'lks2' },
      { t: 'A diagram with labels', band: 'lks2' },
      { t: 'A general opening statement', band: 'uks2' },
      { t: 'Technical vocabulary used accurately', band: 'uks2' },
      { t: 'The passive voice where the doer does not matter', band: 'uks2' },
      { t: 'Subordinate clauses to pack in detail', band: 'uks2' },
      { t: 'A closing that says why it matters', band: 'uks2' },
    ],
    structure: [
      { box: 'Title', hint: 'A question, or a naming phrase' },
      { box: 'What it is', hint: 'One sentence saying what is being explained' },
      { box: 'How it works', hint: 'Each stage in order, each with its reason' },
      { box: 'Why it matters', hint: 'What it means for the reader' },
    ],
    language: {
      openers: ['This happens when', 'The process begins', 'Before this can happen',
        'At this stage', 'Once this is complete', 'The reason for this is',
        'In simple terms', 'To understand this'],
      connectives: ['because', 'so that', 'which means', 'consequently', 'therefore',
        'as a result', 'in order to', 'this causes'],
      vocabulary: ['process', 'stage', 'cause', 'effect', 'function', 'system', 'source',
        'transfer', 'convert', 'rely on'],
    },
    model: '',
  },
  {
    format: 'sage-pack@1',
    kind: 'genre',
    id: 'non-chronological-report',
    name: 'Non-chronological report',
    author: 'Sage Stage',
    note: 'The information text, organised by idea rather than by time. KS1 sorts facts into groups; upper KS2 sounds like an expert who arranged their knowledge for a reader.',
    items: [
      { t: 'A title that says what it is about', band: 'ks1' },
      { t: 'Facts about the subject — not a story about you', band: 'ks1' },
      { t: 'Facts that go together, together', band: 'ks1' },
      { t: 'A picture with a label', band: 'ks1' },
      { t: 'An opening that says what the subject is', band: 'lks2' },
      { t: 'Subheadings to group the information', band: 'lks2' },
      { t: 'Present tense: owls hunt, not owls hunted', band: 'lks2' },
      { t: 'Third person all the way through', band: 'lks2' },
      { t: 'A did-you-know fact to keep the reader reading', band: 'lks2' },
      { t: 'An opening that says what kind of thing the subject is', band: 'uks2' },
      { t: 'Paragraphs that each answer one question', band: 'uks2' },
      { t: 'A formal, impersonal tone', band: 'uks2' },
      { t: 'Technical vocabulary, explained where the reader needs it', band: 'uks2' },
      { t: 'Generalising phrases: most, many, typically, usually', band: 'uks2' },
    ],
    structure: [
      { box: 'Title', hint: 'The subject, plainly' },
      { box: 'What is it?', hint: 'Say what kind of thing it is' },
      { box: 'Section', hint: 'One question answered — Where does it live?' },
      { box: 'Another section', hint: 'The next question — What does it eat?' },
      { box: 'Amazing fact', hint: 'The one the reader will repeat' },
    ],
    language: {
      openers: ['Did you know that', 'There are many types of', 'One of the most remarkable',
        'Surprisingly', 'Unlike most', 'All over the world', 'Scientists have found that',
        'Most famously'],
      connectives: ['also', 'as well as', 'however', 'whereas', 'unlike', 'in fact',
        'for example', 'such as'],
      vocabulary: ['species', 'habitat', 'unique', 'remarkable', 'survive', 'feature',
        'ancient', 'enormous', 'rare', 'located'],
    },
    model: '',
  },
  {
    format: 'sage-pack@1',
    kind: 'genre',
    id: 'persuasion',
    name: 'Persuasion',
    author: 'Sage Stage',
    note: 'Argument and persuasive writing. The upper KS2 criteria are the ones that separate persuading from shouting: the counter-argument answered, and emotive language chosen rather than sprayed.',
    items: [
      { t: 'A title that tells the reader what you want', band: 'ks1' },
      { t: 'Reasons for what you think', band: 'ks1' },
      { t: 'Using “because” to explain a reason', band: 'ks1' },
      { t: 'Words that sound sure: best, must, should', band: 'ks1' },
      { t: 'An opening that states your view clearly', band: 'lks2' },
      { t: 'A reason in each paragraph', band: 'lks2' },
      { t: 'Facts and figures to back a reason up', band: 'lks2' },
      { t: 'Rhetorical questions to make the reader think', band: 'lks2' },
      { t: 'A closing that repeats what you want', band: 'lks2' },
      { t: 'A strong opening — a question, a statistic or a bold claim', band: 'uks2' },
      { t: 'The other side acknowledged, then answered', band: 'uks2' },
      { t: 'Emotive language chosen on purpose', band: 'uks2' },
      { t: 'The rule of three for emphasis', band: 'uks2' },
      { t: 'Modal verbs to press the point', band: 'uks2' },
      { t: 'A closing call to action', band: 'uks2' },
    ],
    structure: [
      { box: 'Title', hint: 'What you want the reader to do' },
      { box: 'Your view', hint: 'State it in one clear sentence' },
      { box: 'Reason', hint: 'The strongest one first, with evidence' },
      { box: 'Another reason', hint: 'A second reason, with evidence' },
      { box: 'The other side', hint: 'Name what they would say, then answer it' },
      { box: 'Call to action', hint: 'Exactly what the reader should do now' },
    ],
    language: {
      openers: ['It is clear that', 'Imagine a world where', 'Surely nobody would argue',
        'Consider this for a moment', 'The evidence is overwhelming', 'Every one of us',
        'How much longer', 'There is no doubt'],
      connectives: ['furthermore', 'in addition', 'however', 'above all', 'therefore',
        'not only that', 'on the other hand', 'most importantly'],
      vocabulary: ['essential', 'unacceptable', 'vital', 'urgently', 'undeniably',
        'shocking', 'deserve', 'demand', 'protect', 'future'],
    },
    model: '',
  },
  {
    format: 'sage-pack@1',
    kind: 'genre',
    id: 'newspaper-report',
    name: 'Newspaper report',
    author: 'Sage Stage',
    note: 'The recount shape at its most disciplined. KS1 works on ordering what happened; KS2 on the tone and the sourcing that make it read like a newspaper rather than a diary.',
    items: [
      { t: 'A headline that makes you want to read on', band: 'ks1' },
      { t: 'Who it happened to, and where', band: 'ks1' },
      { t: 'What happened, in order', band: 'ks1' },
      { t: 'A picture with a caption', band: 'ks1' },
      { t: 'The 5 Ws in the opening paragraph', band: 'lks2' },
      { t: 'Past tense all the way through', band: 'lks2' },
      { t: 'Third person — the reporter never says I or we', band: 'lks2' },
      { t: 'A quote from a witness in inverted commas', band: 'lks2' },
      { t: 'A paragraph for each part of the story', band: 'lks2' },
      { t: 'A headline using wordplay or alliteration', band: 'uks2' },
      { t: 'A subheading that adds information', band: 'uks2' },
      { t: 'A formal, impersonal tone', band: 'uks2' },
      { t: 'Direct and reported speech from more than one source', band: 'uks2' },
      { t: 'A closing paragraph that looks ahead', band: 'uks2' },
    ],
    structure: [
      { box: 'Headline', hint: 'Short and punchy — present tense' },
      { box: 'Opening', hint: 'Who, what, where, when, why — in two sentences' },
      { box: 'What happened', hint: 'The events in the order they happened' },
      { box: 'Quote', hint: 'A witness or an expert speaks' },
      { box: 'Closing', hint: 'What happens next?' },
    ],
    language: {
      openers: ['Yesterday evening', 'Earlier this week', 'Witnesses report that',
        'In a dramatic turn', 'Shortly after midday', 'Local residents say',
        'According to police', 'For the second time this month'],
      connectives: ['however', 'meanwhile', 'as a result', 'furthermore', 'in addition',
        'nevertheless', 'consequently', 'at the same time'],
      vocabulary: ['eyewitness', 'incident', 'reportedly', 'investigation', 'alleged',
        'dramatic', 'scene', 'official', 'confirmed', 'appealed'],
    },
    model: '',
  },
  {
    format: 'sage-pack@1',
    kind: 'genre',
    id: 'playscript',
    name: 'Playscript',
    author: 'Sage Stage',
    note: 'The genre where layout does the talking: no inverted commas, no said — the page itself tells the actors what to do. KS2 moves from getting the conventions right to writing speech worth performing.',
    items: [
      { t: 'The speaker’s name first, then what they say', band: 'ks1' },
      { t: 'No speech marks anywhere', band: 'ks1' },
      { t: 'A new line for each new speaker', band: 'ks1' },
      { t: 'Brackets for what they do: (sits down)', band: 'ks1' },
      { t: 'A cast list at the start', band: 'lks2' },
      { t: 'The scene set in one line: where and when', band: 'lks2' },
      { t: 'A colon after the speaker’s name', band: 'lks2' },
      { t: 'Stage directions in brackets, in the present tense', band: 'lks2' },
      { t: 'Speech that sounds like the character', band: 'lks2' },
      { t: 'Stage directions that show feeling: (backing away slowly)', band: 'uks2' },
      { t: 'Each character with their own way of speaking', band: 'uks2' },
      { t: 'A new scene when the place or time changes', band: 'uks2' },
      { t: 'Speech that moves the scene on', band: 'uks2' },
      { t: 'Everything the audience needs, carried by the speech', band: 'uks2' },
    ],
    structure: [
      { box: 'Cast', hint: 'Who is in it, one line each' },
      { box: 'Scene', hint: 'Where and when, in one line' },
      { box: 'Opening', hint: 'Who speaks first — and why now?' },
      { box: 'The turn', hint: 'The moment something changes' },
      { box: 'Curtain', hint: 'The line you leave the audience with' },
    ],
    language: {
      openers: ['Scene 1', 'Later that day', 'That evening', 'Meanwhile, offstage',
        'The next morning', 'Back at the house', 'Moments later', 'At the edge of the stage'],
      connectives: ['anyway', 'by the way', 'come to think of it', 'as I was saying',
        'hold on', 'in that case', 'after all', 'mind you'],
      vocabulary: ['enters', 'exits', 'aside', 'offstage', 'pause', 'whispers', 'gasps',
        'shrugs', 'storms off', 'curtain'],
    },
    model: '',
  },
  {
    format: 'sage-pack@1',
    kind: 'genre',
    id: 'poetry',
    name: 'Poetry',
    author: 'Sage Stage',
    note: 'The one genre whose rules are chosen per poem — so these criteria are about choices, not rules. KS1 plays with sound; upper KS2 works on image and economy, every word earning its line.',
    items: [
      { t: 'Words that start with the same sound', band: 'ks1' },
      { t: 'Rhymes — if the poem wants them', band: 'ks1' },
      { t: 'A pattern that repeats', band: 'ks1' },
      { t: 'Sound words: crash, pop, whisper', band: 'ks1' },
      { t: 'Similes using like or as', band: 'lks2' },
      { t: 'Alliteration chosen for effect', band: 'lks2' },
      { t: 'A picture painted in each verse', band: 'lks2' },
      { t: 'Line breaks where you want the reader to pause', band: 'lks2' },
      { t: 'Powerful verbs instead of piled-up adjectives', band: 'lks2' },
      { t: 'Metaphor: saying it is, not it is like', band: 'uks2' },
      { t: 'Personification to bring things alive', band: 'uks2' },
      { t: 'One mood, kept all the way through', band: 'uks2' },
      { t: 'Every word earning its place — cut the ones that don’t', band: 'uks2' },
      { t: 'Sound matching sense: soft sounds for soft things', band: 'uks2' },
      { t: 'A last line that lands', band: 'uks2' },
    ],
    structure: [
      { box: 'The idea', hint: 'What is this poem looking at?' },
      { box: 'First image', hint: 'Show it — don’t explain it' },
      { box: 'It grows', hint: 'Each verse adds or changes something' },
      { box: 'The turn', hint: 'Where the poem surprises' },
      { box: 'Last line', hint: 'The one they remember' },
    ],
    language: {
      openers: ['I have seen', 'Imagine', 'In the deep of', 'Beneath', 'When the wind',
        'Once, long ago', 'Listen —', 'At the edge of'],
      connectives: ['and then', 'until', 'while', 'as if', 'like', 'though', 'still',
        'even now'],
      vocabulary: ['shimmer', 'crackle', 'drift', 'hollow', 'silver', 'ancient', 'murmur',
        'blaze', 'tangled', 'silent'],
    },
    model: '',
  },
  {
    format: 'sage-pack@1',
    kind: 'genre',
    id: 'book-review',
    name: 'Book review',
    author: 'Sage Stage',
    note: 'Opinion with evidence, practised on a book. KS1 says what it was about and what they thought; upper KS2 recommends to a named reader, quotes as evidence, and never gives away the ending.',
    items: [
      { t: 'The title and the author', band: 'ks1' },
      { t: 'What the book is about, in a sentence or two', band: 'ks1' },
      { t: 'Your favourite part, and why', band: 'ks1' },
      { t: 'Would you tell a friend to read it?', band: 'ks1' },
      { t: 'A summary that doesn’t give away the ending', band: 'lks2' },
      { t: 'Your opinion, with a because', band: 'lks2' },
      { t: 'What the author does well, with an example', band: 'lks2' },
      { t: 'The main character described in a sentence', band: 'lks2' },
      { t: 'A score out of five, with the reason for it', band: 'lks2' },
      { t: 'A comparison to books the reader might know', band: 'uks2' },
      { t: 'Short quotes from the book as evidence', band: 'uks2' },
      { t: 'Balanced: something that worked, something that didn’t', band: 'uks2' },
      { t: 'A comment on the author’s style, with an example', band: 'uks2' },
      { t: 'A recommendation that names its reader: perfect for anyone who…', band: 'uks2' },
    ],
    structure: [
      { box: 'The book', hint: 'Title, author — and the genre, if it helps' },
      { box: 'What it is about', hint: 'Two sentences, no spoilers' },
      { box: 'What I thought', hint: 'Opinions, each with a because' },
      { box: 'Best bit', hint: 'A moment or a quality, with evidence' },
      { box: 'Who should read it', hint: 'Name the reader, give the score' },
    ],
    language: {
      openers: ['This book tells the story of', 'From the very first page',
        'The best thing about this book is', 'What I loved most was', 'If you enjoy',
        'By the end', 'My only complaint is', 'I would recommend this to'],
      connectives: ['because', 'although', 'however', 'for example', 'in particular',
        'despite this', 'overall', 'on balance'],
      vocabulary: ['gripping', 'hilarious', 'moving', 'predictable', 'vivid', 'character',
        'plot', 'chapter', 'illustration', 'recommend'],
    },
    model: '',
  },
];
